<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mapping the Soul’s Journey: A Text Analysis of the Egyptian Book of the Dead</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/popper.min.js"></script>
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BozSude_McGarveyClare_TMFinalAssignment_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BozSude_McGarveyClare_TMFinalAssignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BozSude_McGarveyClare_TMFinalAssignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BozSude_McGarveyClare_TMFinalAssignment_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mapping the Soul’s Journey: A Text Analysis of the Egyptian Book of the Dead</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Clare McGarvey &amp; Sude Boz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="the-egyptian-book-of-the-dead-by-p.-le-page-renouf-and-edouard-naville" class="level1">
<h1><strong>The Egyptian Book of the dead</strong> by P. Le Page Renouf and Edouard Naville</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The Egyptian Book of the Dead, sometimes directly translated as the book of ‘coming forth by day’ or ‘coming out of the day’, is a collection of various Ancient Egyptian theological texts designed to assist one with the passage into the afterlife. The collection grew and changed over the course of the civilisation, becoming somewhat standardised during the 26th Dynasty, and contains spells, hymns, prayers and instructions used by the deceased to successfully pass into the afterlife. Originally beginning as inscriptions on the walls of Pharaohs, these funerary texts were adopted by the upper-middle classes around the New Kingdom (1550–1070 BCE) and became an important component of Ancient Egyptian death rites. They were commissioned for the individual and therefore the content and its arrangement varied considerably from book to book. This edition was translated from the original hieroglyphics by P. Le Page Renouf and Edouard Naville, being completed in 1904.</p>
</section>
<section id="set-up" class="level2">
<h2 class="anchored" data-anchor-id="set-up">Set-up</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epubr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(textdata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>raw_epub <span class="ot">&lt;-</span> <span class="fu">epub</span>(<span class="st">"pg69566-images.epub"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>epub_sections <span class="ot">&lt;-</span> raw_epub<span class="sc">$</span>data[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="splitting-into-chapters" class="level3">
<h3 class="anchored" data-anchor-id="splitting-into-chapters">Splitting into Chapters</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>death_book <span class="ot">&lt;-</span> epub_sections <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(text, <span class="fu">regex</span>(<span class="st">"all full-page.*plates have been moved"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ignore_case =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">line =</span> <span class="fu">str_split</span>(text, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>text) <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(line) <span class="sc">|&gt;</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">linenumber =</span> <span class="fu">row_number</span>(),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">line =</span> <span class="fu">str_trim</span>(line)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(line <span class="sc">!=</span> <span class="st">""</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">chapter =</span> <span class="fu">cumsum</span>(</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(line, <span class="fu">regex</span>(<span class="st">"^CHAPTERS? [IVXLC]"</span>)) <span class="sc">&amp;</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>      <span class="sc">!</span><span class="fu">str_detect</span>(line, <span class="st">"="</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">text =</span> line)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Check</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>death_book <span class="sc">|&gt;</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(<span class="fu">str_trim</span>(text), <span class="fu">regex</span>(<span class="st">"^CHAPTERS? [IVXLC]"</span>)) <span class="sc">&amp;</span> </span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">str_detect</span>(text, <span class="st">"="</span>)) <span class="sc">|&gt;</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(linenumber, chapter, text)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 181 × 3
   linenumber chapter text         
        &lt;int&gt;   &lt;int&gt; &lt;chr&gt;        
 1       1063       1 CHAPTER I.   
 2       1450       2 CHAPTER II.  
 3       1486       3 CHAPTER III. 
 4       1523       4 CHAPTER IV.  
 5       1628       5 CHAPTER VI.  
 6       1663       6 CHAPTER VII. 
 7       1710       7 CHAPTER VIII.
 8       1753       8 CHAPTER IX.  
 9       1780       9 CHAPTER X.   
10       1795      10 CHAPTER XI.  
# ℹ 171 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write.csv(death_book, "death_book.csv")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="removing-editors-notes" class="level3">
<h3 class="anchored" data-anchor-id="removing-editors-notes">Removing Editor’s Notes</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>death_lines <span class="ot">&lt;-</span> death_book <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(chapter <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">str_remove_all</span>(text, <span class="st">"_"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_squish</span>(text) <span class="sc">!=</span> <span class="st">""</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(chapter) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">notes_start =</span> <span class="fu">cumsum</span>(<span class="fu">str_detect</span>(<span class="fu">str_trim</span>(text), </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                                    <span class="fu">regex</span>(<span class="st">"^Notes?</span><span class="sc">\\</span><span class="st">.?$|^Note</span><span class="sc">\\</span><span class="st">.$"</span>)))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(notes_start <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(<span class="fu">str_trim</span>(text), <span class="fu">regex</span>(<span class="st">"^</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">s*</span><span class="sc">\\</span><span class="st">.?</span><span class="sc">\\</span><span class="st">s*$"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(text, <span class="fu">regex</span>(<span class="st">"footnote|see note|</span><span class="sc">\\</span><span class="st">bpl</span><span class="sc">\\</span><span class="st">."</span>, </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">ignore_case =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(<span class="fu">str_trim</span>(text),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>         <span class="fu">regex</span>(<span class="st">"^plate |^fig</span><span class="sc">\\</span><span class="st">.|^vignette"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_squish</span>(text) <span class="sc">!=</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lines mentioning notes/footnote</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>death_lines <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(text, <span class="fu">regex</span>(<span class="st">"footnote|</span><span class="sc">\\</span><span class="st">bнote</span><span class="sc">\\</span><span class="st">b"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(linenumber, chapter, text)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 3
# ℹ 3 variables: linenumber &lt;int&gt;, chapter &lt;int&gt;, text &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for editorial content</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>death_lines <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(<span class="fu">str_trim</span>(text), <span class="fu">regex</span>(<span class="st">"^</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">."</span>))) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(linenumber, chapter, text) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 3
   linenumber chapter text                                                      
        &lt;int&gt;   &lt;int&gt; &lt;chr&gt;                                                     
 1       3062      16 1. Oh Thoth, who makest Osiris triumphant over his advers…
 2       3072      16 2. Oh Thoth who makest Osiris triumphant over his adversa…
 3       3080      16 3. Oh Thoth who makest Osiris triumphant over his adversa…
 4       3087      16 4. Oh Thoth, who makest Osiris triumphant over his advers…
 5       3095      16 5. Oh Thoth, who makest Osiris triumphant over his advers…
 6       3102      16 6. Oh Thoth, who makest Osiris triumphant over his advers…
 7       3109      16 7. Oh Thoth, who makest Osiris triumphant over his advers…
 8       3118      16 8. Oh Thoth, who makest Osiris triumphant over his advers…
 9       3127      16 9. Oh Thoth, who makest Osiris triumphant over his advers…
10       3136      16 10. Oh Thoth, who makest Osiris triumphant over his adver…
# ℹ 20 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for scholarly language that signals editor prose, not ritual text</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>death_lines <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(text, <span class="fu">regex</span>(<span class="st">"papyrus|manuscript|dynasty|translation|lepsius|naville"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">ignore_case =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(linenumber, chapter, text) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 3
   linenumber chapter text                                                      
        &lt;int&gt;   &lt;int&gt; &lt;chr&gt;                                                     
 1       6892      76 following. In the papyrus of Nebseni the name has for det…
 2       8305     101 a strip of royal papyrus, put at the throat of the deceas…
 3       9205     116 and his papyrus,(5) and his attendant gods, and his chief…
 4      12165     132 Sutu,(4) Nephthys, painted yellowish green on a fresh pap…
 5      12578     139 This completes Sir P. Le Page Renouf's translation of the…
 6      12585     139 By Edouard Naville, D.C.L., &amp;c., &amp;c.                      
 7      12595     139 been striving to attain, the completion of his translatio…
 8      12611     139 line of written translation left, beyond what he printed …
 9      12612     139 Thus, for the translation of the following chapters, I wa…
10      12623     139 Thus it cannot be said absolutely that this translation i…
11      12627     139 any translation of the Book of the Dead is tentative and …
12      12632     139 EDOUARD NAVILLE.                                          
13      14889     158 neck of the deceased. Also if it is painted on new papyru…
14      15324     164 very fragmentary. The most complete, papyrus 10478 of the…
15      16691     180 three words remain. They are taken from a papyrus in Pari…</code></pre>
</div>
</div>
<p>Although some editorial notes remain after cleaning, their presence does not meaningfully affect the analysis.</p>
</section>
<section id="normalising-transliteration-characters" class="level3">
<h3 class="anchored" data-anchor-id="normalising-transliteration-characters">Normalising Transliteration Characters</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalizing Egyptian transliteration characters to plain ASCII</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>death_lines <span class="ot">&lt;-</span> death_lines <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">str_replace_all</span>(text, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"ā"</span> <span class="ot">=</span> <span class="st">"a"</span>, <span class="st">"ē"</span> <span class="ot">=</span> <span class="st">"e"</span>, <span class="st">"ī"</span> <span class="ot">=</span> <span class="st">"i"</span>, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">"ō"</span> <span class="ot">=</span> <span class="st">"o"</span>, <span class="st">"ū"</span> <span class="ot">=</span> <span class="st">"u"</span>, <span class="st">"Ā"</span> <span class="ot">=</span> <span class="st">"a"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">"ȧ"</span> <span class="ot">=</span> <span class="st">"a"</span>, <span class="st">"â"</span> <span class="ot">=</span> <span class="st">"a"</span>, <span class="st">"î"</span> <span class="ot">=</span> <span class="st">"i"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="stop-words" class="level3">
<h3 class="anchored" data-anchor-id="stop-words">Stop Words</h3>
<p>Since the book is an old book, it consists Archaic English words and vocabulary, we decided to treat and tibble them as <code>custom_stopwords</code>`. In addition, we put “editorial, apparatus words and roman numerals that survive lowercasing” as custom_stopwords as well.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Archaic English forms and editorial/apparatus vocabulary</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>custom_stops <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">word =</span> <span class="fu">c</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># archaic English pronouns and verb forms</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"thy"</span>, <span class="st">"thou"</span>, <span class="st">"thee"</span>, <span class="st">"hath"</span>, <span class="st">"doth"</span>, <span class="st">"thereof"</span>, <span class="st">"therein"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"hast"</span>, <span class="st">"art"</span>, <span class="st">"thine"</span>, <span class="st">"ye"</span>, <span class="st">"unto"</span>, <span class="st">"shalt"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># editorial and apparatus words</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"text"</span>, <span class="st">"texts"</span>, <span class="st">"word"</span>, <span class="st">"words"</span>, <span class="st">"note"</span>, <span class="st">"notes"</span>, <span class="st">"footnote"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"translation"</span>, <span class="st">"found"</span>, <span class="st">"called"</span>, <span class="st">"sense"</span>, <span class="st">"book"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"papyrus"</span>, <span class="st">"papyri"</span>, <span class="st">"egyptian"</span>, <span class="st">"chapter"</span>, <span class="st">"chapters"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"written"</span>, <span class="st">"turin"</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># roman numerals that survive lowercasing</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ii"</span>, <span class="st">"iii"</span>, <span class="st">"iv"</span>, <span class="st">"vi"</span>, <span class="st">"vii"</span>, <span class="st">"viii"</span>, <span class="st">"ix"</span>, <span class="st">"xi"</span>, <span class="st">"xii"</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="tokenise" class="level3">
<h3 class="anchored" data-anchor-id="tokenise">Tokenise</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="ot">&lt;-</span> death_lines <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_tokens</span>(word, text) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(word, <span class="st">"^[a-z]+$"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(stop_words) <span class="sc">|&gt;</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(custom_stops)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(word)`
Joining with `by = join_by(word)`</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>tidy_death</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18,998 × 7
   section nword nchar linenumber chapter notes_start word        
   &lt;chr&gt;   &lt;int&gt; &lt;int&gt;      &lt;int&gt;   &lt;int&gt;       &lt;int&gt; &lt;chr&gt;       
 1 f1       3964 22416       1065       1           0 beginning   
 2 f1       3964 22416       1065       1           0 coming      
 3 f1       3964 22416       1065       1           0 day         
 4 f1       3964 22416       1065       1           0 bring       
 5 f1       3964 22416       1065       1           0 resurrection
 6 f1       3964 22416       1065       1           0 glory       
 7 f1       3964 22416       1065       1           0 coming      
 8 f1       3964 22416       1065       1           0 entering    
 9 f1       3964 22416       1065       1           0 amenta      
10 f1       3964 22416       1065       1           0 day         
# ℹ 18,988 more rows</code></pre>
</div>
</div>
</section>
<section id="chapter-length" class="level3">
<h3 class="anchored" data-anchor-id="chapter-length">Chapter Length</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter, <span class="at">sort =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(n) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 2
   chapter     n
     &lt;int&gt; &lt;int&gt;
 1     123     1
 2      73     2
 3     127     2
 4      48     3
 5     110     3
 6     180     5
 7      61     7
 8     107     8
 9       4    10
10     103    10
# ℹ 30 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter, <span class="at">sort =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   chapter     n
     &lt;int&gt; &lt;int&gt;
 1     122   860
 2      14   644
 3     144   638
 4      15   628
 5      78   512
 6     168   496
 7      16   481
 8      64   416
 9     116   370
10     128   366
11     179   346
12     165   333
13     141   314
14     174   311
15     176   299
16     177   293
17      42   282
18     178   281
19      99   276
20     142   275</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_words =</span> <span class="fu">mean</span>(n),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_words =</span> <span class="fu">median</span>(n),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_words =</span> <span class="fu">min</span>(n),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_words =</span> <span class="fu">max</span>(n),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_chapters =</span> <span class="fu">n</span>()</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  mean_words median_words min_words max_words total_chapters
       &lt;dbl&gt;        &lt;int&gt;     &lt;int&gt;     &lt;int&gt;          &lt;int&gt;
1       105.           53         1       860            181</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write.csv(tidy_death, "tidy_death.csv")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>One hundred and eighty one chapters have been identified, with the chapters varying considerably in length, ranging from containing 1 non-stopword to 860. The mean words is 105 per chapter but the median is 53, indicating that a few long chapters inflate the average. Eight chapters contain less than 10 non-stopwords, half of which just indicate that the chapter is a repetition of a previous chapter. The others are short phrases, aside from chapter 123 which is split into three short parts and wasn’t coded properly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking which chapters were not matched</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>detected_numerals <span class="ot">&lt;-</span> death_book <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(<span class="fu">str_trim</span>(text), <span class="fu">regex</span>(<span class="st">"^CHAPTERS? [IVXLC]"</span>)) <span class="sc">&amp;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">str_detect</span>(text, <span class="st">"="</span>)) <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">numeral =</span> <span class="fu">str_extract</span>(<span class="fu">str_trim</span>(text), </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">regex</span>(<span class="st">"(?&lt;=CHAPTERS? )[IVXLC]+"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(numeral)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Chapter names from index</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>expected_numerals <span class="ot">&lt;-</span> epub_sections <span class="sc">|&gt;</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">line =</span> <span class="fu">str_split</span>(text, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>text) <span class="sc">|&gt;</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(line) <span class="sc">|&gt;</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">line =</span> <span class="fu">str_trim</span>(line)) <span class="sc">|&gt;</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(line, <span class="fu">regex</span>(<span class="st">"^[IVXLC]+</span><span class="sc">\\</span><span class="st">.$"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">numeral =</span> <span class="fu">str_remove</span>(line, <span class="st">"</span><span class="sc">\\</span><span class="st">."</span>)) <span class="sc">|&gt;</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(numeral) <span class="sc">|&gt;</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing chapters</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>missing_numerals <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(expected_numerals, detected_numerals)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>missing_numerals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "V"       "XVI"     "LXII"    "CXLIV"   "CL"      "CLXXXVI"</code></pre>
</div>
</div>
<p>Five chapters were not correctly identified: V, XVI, LXXI, CXLIV, CL, CLXXXVI. Due to the size and nature of the text, this is an understandable misallocation, however, it should be noted that the chapter numbers quoted by R may not exactly align with the chapter numbers from the text.</p>
</section>
<section id="count-the-frequencies" class="level3">
<h3 class="anchored" data-anchor-id="count-the-frequencies">Count the frequencies</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,068 × 2
   word       n
   &lt;chr&gt;  &lt;int&gt;
 1 osiris   350
 2 gods     335
 3 ra       330
 4 god      234
 5 horus    186
 6 lord     175
 7 day      165
 8 earth    146
 9 heaven   122
10 heart    116
# ℹ 4,058 more rows</code></pre>
</div>
</div>
</section>
<section id="preliminary-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="preliminary-data-analysis">Preliminary Data Analysis</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">150</span>) <span class="sc">|&gt;</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">word =</span> <span class="fu">reorder</span>(word, n)) <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(n, word)) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Trying the same plot with words that are mentioned fewer times:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">70</span>) <span class="sc">|&gt;</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">word =</span> <span class="fu">reorder</span>(word, n)) <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(n, word)) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the preliminary analysis it is clear that the text is theological. The words “Gods”, “God”, “Lord”, “heaven”, “earth”, divine”, “heart”, “soul”, “father” and “sky” all appear in the top 20 most frequent terms in the text. The most frequently used word of all is “Osiris”, the Ancient Egyptian deity who ruled the realm of the dead, followed by “Ra”, the sun God and arguably Ancient Egypt’s most important deity (Wilkinson, 2003), and “Horus”, Osiris’ son who was associated with kingship and the social restoration of the deceased (Assmann, 2005, ch.&nbsp;1). Other common terms specific to Ancient Egyptian theology include “Thoth”, the moon God who prescribes over scribes and serves Osiris, and the “Netherworld” also referred to the “Tuat” in the text which is realm the soul traverses after death (Wilkinson, 2003). Despite an absence of terms that explicitly reference death, the most frequent words indicate that the text is deeply spiritual, with specific concern for the afterlife.</p>
</section>
</section>
</section>
<section id="text-mining-techniques" class="level1">
<h1>Text Mining Techniques</h1>
<ul>
<li><p><strong>TF-IDF</strong></p>
<p>The book is a collection of thematically distinct ritual chapters, making it an ideal candidate for a technique that rewards words which are frequent in one document but rare across the rest. So, we decided to use TF-IDF for the first technique.</p></li>
<li><p><strong>Sentiment Analysis</strong></p>
<p>Even though TF-IDF is good at showing the distinctive vocabulary of the book, tells us nothing about the emotional tone of the text. For a funerary document whose stated purpose is to guide and reassure the dead, the emotional register is as analytically meaningful as the words themselves. That is why sentiment analysis is chosen to use as the second technique. Furthermore, the NRC lexicon was selected over Bing or AFINN because it distinguishes between eight discrete emotions.</p></li>
</ul>
<section id="tf-idf" class="level2">
<h2 class="anchored" data-anchor-id="tf-idf">1) TF-IDF</h2>
<section id="set-up-1" class="level3">
<h3 class="anchored" data-anchor-id="set-up-1">Set-up</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>chapter_words <span class="ot">&lt;-</span> tidy_death <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter, word, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>chapter_words</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13,025 × 3
   chapter word            n
     &lt;int&gt; &lt;chr&gt;       &lt;int&gt;
 1     122 appearance     44
 2     122 makest         42
 3      16 osiris         36
 4      16 adversaries    34
 5     128 osiris         31
 6      16 triumphant     30
 7      16 gods           29
 8     144 domain         27
 9      68 possession     26
10      16 circle         24
# ℹ 13,015 more rows</code></pre>
</div>
</div>
<p>This table illustrates the number of times each word appears in each chapter, in descending order. Since chapter length is not uniform, the pure count is not overly informative as words appear in greater number just because that chapter is much longer than others.</p>
<p>Chapters with few words are unstable for use with TF-IDF, as a word mentioned only minimally may appear to dominate the chapter, thus artificially inflating the score. Therefore chapters with less than 20 words after stop word removal are not utilised in the TF-IDF analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering Chapters</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>valid_chapters <span class="ot">&lt;-</span> tidy_death <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(chapter)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>chapter_words <span class="ot">&lt;-</span> chapter_words <span class="sc">|&gt;</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(chapter <span class="sc">%in%</span> valid_chapters)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="scores" class="level3">
<h3 class="anchored" data-anchor-id="scores">Scores</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TF-IDF</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>chapter_tfidf <span class="ot">&lt;-</span> chapter_words <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_tf_idf</span>(word, chapter, n)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Highest scoring words</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>chapter_tfidf <span class="sc">|&gt;</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(tf_idf))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,728 × 6
   chapter word             n     tf   idf tf_idf
     &lt;int&gt; &lt;chr&gt;        &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1      37 merta            3 0.15    3.94  0.591
 2      74 faint            4 0.148   3.65  0.541
 3      88 crocodile        3 0.15    3.43  0.514
 4     151 tat              4 0.118   3.94  0.463
 5     136 kindled          4 0.105   4.34  0.457
 6      95 assault          2 0.1     4.34  0.434
 7     112 nechen           9 0.0928  4.34  0.403
 8       9 victoriously     2 0.0769  5.04  0.387
 9      12 adore            2 0.0952  3.94  0.375
10      68 possession      26 0.183   2.04  0.374
# ℹ 12,718 more rows</code></pre>
</div>
</div>
<p>Individual chapters that display distinctive terms within the book are quite varied. Chapter 37 references ‘Merta’, the sister pair of Goddesses Isis and Nephthys 3 times, 15% of all words in the chapter. The terms “faint” and “crocodile”, in chapters 74 and 88 respectively, also make up around 15% of their chapters, an unusual occurrence in other forms of literature but more typical of short prayers and hymns as collected here.</p>
<p>Other chapter themes that seem to be distinct within the collection are 112 which talks of Nechen, the ancient city that severed as the religious and political centre of prehistoric Egypt, chapter 9 and 12 which reference a victorious action and adoration respectively, and chapter 68 which is concerned with possession. Interestingly, the only divinities that are distinct of a chapter is the pair Merta, indicating that the others are referenced throughout the book and are not unique to any one chapter.</p>
</section>
<section id="section-analysis" class="level3">
<h3 class="anchored" data-anchor-id="section-analysis">Section Analysis</h3>
<p>As these Ancient Egyptian funerary texts were produced specifically for a given customer, they were not uniform in structure or content, instead including the instructions and spells deemed individually most necessary. For example, the Book of Ani, the largest and best preserved book of the dead, contains less than one half of the chapters commonly ascribed to versions of that time and place (Wallis Budge, 1895). There is an assumption that relatives of the dying or deceased selected sections from the full collection at their scribe’s disposal, based on what was deemed most useful for their passage and at a length they could afford (“Introduction,” 1904/2022).</p>
<p>From the 26th Dynasty (the Saïte Period) the text was seemingly standardised and a more rigid and widespread order was adopted (Barguet, 1967). Spells were arranged in a uniform sequence, following the structure:</p>
<ul>
<li>Chapters 1-16: Entering the underworld</li>
<li>Chapters 17-63: Mythic origins and rebirth</li>
<li>Chapters 64-129: Journey across the sky</li>
<li>Chapters 130-189: Final vindication</li>
</ul>
<p>To test whether this edition of the book is aligned with editions of the Saïte Period, TF-IDF will be employed to examine what aspects distinguish each section from the others.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sections based on the Saite period ordering</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>chapter_tfidf <span class="ot">&lt;-</span> chapter_tfidf <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">section =</span> <span class="fu">case_when</span>(</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">1</span>  <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">14</span>  <span class="sc">~</span> <span class="st">"I: Entering the Underworld</span><span class="sc">\n</span><span class="st">(Ch. 1–16)"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">15</span> <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">62</span>  <span class="sc">~</span> <span class="st">"II: Mythic Origins &amp; Rebirth</span><span class="sc">\n</span><span class="st">(Ch. 17–63)"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">63</span> <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">127</span> <span class="sc">~</span> <span class="st">"III: Journey Across the Sky</span><span class="sc">\n</span><span class="st">(Ch. 64–129)"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">128</span>                 <span class="sc">~</span> <span class="st">"IV: Vindication &amp; Power</span><span class="sc">\n</span><span class="st">(Ch. 130–189)"</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">section =</span> <span class="fu">factor</span>(section, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I: Entering the Underworld</span><span class="sc">\n</span><span class="st">(Ch. 1–16)"</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"II: Mythic Origins &amp; Rebirth</span><span class="sc">\n</span><span class="st">(Ch. 17–63)"</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"III: Journey Across the Sky</span><span class="sc">\n</span><span class="st">(Ch. 64–129)"</span>,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IV: Vindication &amp; Power</span><span class="sc">\n</span><span class="st">(Ch. 130–189)"</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  )))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate to section level</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>section_words <span class="ot">&lt;-</span> tidy_death <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(chapter <span class="sc">%in%</span> valid_chapters, chapter <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">section =</span> <span class="fu">case_when</span>(</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">1</span>  <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">14</span>  <span class="sc">~</span> <span class="st">"I: Entering the Underworld"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">15</span> <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">62</span>  <span class="sc">~</span> <span class="st">"II: Mythic Origins &amp; Rebirth"</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">63</span> <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">127</span> <span class="sc">~</span> <span class="st">"III: Journey Across the Sky"</span>,</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">128</span>                 <span class="sc">~</span> <span class="st">"IV: Vindication &amp; Power"</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">section =</span> <span class="fu">factor</span>(section, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I: Entering the Underworld"</span>,</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"II: Mythic Origins &amp; Rebirth"</span>,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"III: Journey Across the Sky"</span>,</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IV: Vindication &amp; Power"</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  ))) <span class="sc">|&gt;</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(section, word, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="co"># TF-IDF with section as the document unit</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>section_tfidf <span class="ot">&lt;-</span> section_words <span class="sc">|&gt;</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_tf_idf</span>(word, section, n)</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot most distinctive words per section</span></span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>section_tfidf <span class="sc">|&gt;</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(section) <span class="sc">|&gt;</span></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(tf_idf, <span class="at">n =</span> <span class="dv">15</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">word =</span> <span class="fu">reorder</span>(word, tf_idf)) <span class="sc">|&gt;</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tf_idf, word, <span class="at">fill =</span> section)) <span class="sc">+</span></span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"TF-IDF score"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Most distinctive words per theological section"</span>,</span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Egyptian Book of the Dead- Saite period ordering"</span></span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>section, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Splitting the book into four sections, the first section is especially ceremonial, with a focus on paralysation. Ancient Egyptians believed that at death the various aspects that constitute a person, such as the physical body and the different forms of the soul, were temporarily severed. In order to progress into the next realm re-unification had to occur (Taylor, 2010). The first section seems to align with this initial stage, with distinct focus on “reconcil[ing]” and “aris[ing]”. ‘Unclose’ refers to rituals that open the deceased mouth, eyes and limbs so that they may use them in the netherworld. The God that is distinct to this section is Sokaru, a funeral deity and the patron saint of the large Memphite necropolis, said to guard the mouth of the passages into the netherworld (Hart, 1986). Additionally, there is a focus on exultation and victory, painting the section as one of triumph.</p>
<p>“Circle” is the most distinct word of the second section, which is almost always in reference to the “Great Circle of the Gods” and invokes divine cycles. References to Apep, the Ancient Egyptian deity of chaos and enemy of Rā, also dominates the second section as does the term “triumphant”. Additionally, the Egyptian deity Sut, who murdered his brother Osiris, is a distinct figure in this section and along with terms like “severed”, “execution” and “execratest” (to denounce) which indicates a retelling of the original Osiris myth. This along with the distinct terms “defeat”, “battle” and “power” indicating this section appertains to Orisis’ victory over his adversaries. Generally, this section appears to reference a mythical battle between opposing forces and the triumph of one over the other, revealing the deceased must understand and be ready to re-enact the origin of creation.</p>
<p>The third section references “hotep”, an Egyptian word that roughly translates as ‘rest’ or ‘peace’, revealing a distinct shift in the journey wherein the deceased is now tranquil, evident also in its talk of a garden. The prehistoric Egyptian city of Nechen and the ancient city of Annu are also distinct of this section, potentially stops along the solar journey. Third person verbs such as ‘assumeth’, ‘maketh’, ‘pleaseth’, ‘revealest’ and ‘disrobest’ suggests that this section contains more direct proclamations or pleas to the gods. Reckoning and righteousness indicate a judgement, and ‘divine’, ‘glorified’ and ‘sacred’ allude to reaching the afterlife post-judgement. The section uses material language more than others, discussing a ‘garden’, ‘cubits’, ‘swine’, ‘cake’ and ‘battlements’, associated with the Field of Reeds, the paradise that awaits vindicated souls.</p>
<p>The fourth section “Vindication and Power” is defined by the word ‘pylon’, monumental Ancient Egyptian temple gates, indicating arrival and passage. Amon refers to the creator deity and king of the gods (Wilkinson, 2003) and ka references the life-force part of the soul, interesting appearing here at the end more than at any other part of the book. Procedural language is unique to this section, with ‘prepare’, ‘painted’, and ‘enwrapping’ illustrating instructions or ritual. There is more focus on beauty, soul, gates, praise and rest in this concluding section. Representing a finality and a version of the afterlife which utilises symbolism and imagery similar to that of the Christian idea of heaven.</p>
<p>The Tf-IDF analysis reveals that the vocabulary shifts distinctly over the four sections of the text, depicting a broad theological arc aligned with that put forth by Barguet. Section I is largely defined by ceremonial language, reflecting the formal beginning of the funerary ritual wherein the deceased is reunited with the body. Section II retells the epic mythology of divine creation and through section III a judgement and passage into a sacred realm. Finally, section IV is defined by architectural and devotional language as the deceased finally reaches a place of absolution.</p>
</section>
</section>
<section id="zipfs-law" class="level2">
<h2 class="anchored" data-anchor-id="zipfs-law">Zipf’s Law</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>chapter_tfidf <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tf)) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>, <span class="at">bins =</span> <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="cn">NA</span>, <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"term frequency"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"number of words"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Term frequency distribution across all chapters"</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Long-tail distribution consistent with Zipf's law"</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 243 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>freq_by_rank <span class="ot">&lt;-</span> tidy_death <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(chapter, word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(chapter) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># term frequency = times word appears / total words in chapter</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">total =</span> <span class="fu">sum</span>(n),</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">term_frequency =</span> n <span class="sc">/</span> total,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># rank within chapter — rank 1 = most frequent word in that chapter</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">rank =</span> <span class="fu">row_number</span>()</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>freq_by_rank</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13,025 × 6
   chapter word            n total term_frequency  rank
     &lt;int&gt; &lt;chr&gt;       &lt;int&gt; &lt;int&gt;          &lt;dbl&gt; &lt;int&gt;
 1     122 appearance     44   860         0.0512     1
 2     122 makest         42   860         0.0488     2
 3      16 osiris         36   481         0.0748     1
 4      16 adversaries    34   481         0.0707     2
 5     128 osiris         31   366         0.0847     1
 6      16 triumphant     30   481         0.0624     3
 7      16 gods           29   481         0.0603     4
 8     144 domain         27   638         0.0423     1
 9      68 possession     26   142         0.183      1
10      16 circle         24   481         0.0499     5
# ℹ 13,015 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>rank_subset <span class="ot">&lt;-</span> freq_by_rank <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rank <span class="sc">&gt;=</span> <span class="dv">5</span>, rank <span class="sc">&lt;=</span> <span class="dv">200</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">log10</span>(term_frequency) <span class="sc">~</span> <span class="fu">log10</span>(rank), <span class="at">data =</span> rank_subset)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log10(term_frequency) ~ log10(rank), data = rank_subset)

Coefficients:
(Intercept)  log10(rank)  
    -0.8060      -0.7906  </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>freq_by_rank <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(rank, term_frequency, <span class="at">colour =</span> <span class="fu">as.factor</span>(chapter))) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="sc">-</span><span class="fl">0.8060</span>, <span class="at">slope =</span> <span class="sc">-</span><span class="fl">0.7906</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"rank (log scale)"</span>,</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"term frequency (log scale)"</span>,</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Zipf's Law in the Egyptian Book of the Dead"</span>,</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Dashed line shows ideal Zipf distribution"</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/Plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The term frequency distribution reveals that this 3000 year old Ancient Egyptian text, translated into Victorian English, follows Zipf’s law wherein most words have low term frequencies while a small number appear more rarely but carry specific information.</p>
</section>
</section>
<section id="sentiment-analysis" class="level1">
<h1>2) Sentiment Analysis</h1>
<section id="sentiment-analysis-across-the-four-sections" class="level2">
<h2 class="anchored" data-anchor-id="sentiment-analysis-across-the-four-sections">Sentiment analysis across the four sections</h2>
<p>Question we desire to find out about the book is<em>: Does the emotional register of the spells change as the soul progresses from entering the underworld to final vindication?</em></p>
<p>In this way, we believe that we will be able to understand and observe the emotional language and tone of the book and if it changes across the sections.</p>
<p>We decided to use NRC lexicon since it has 8 wide and specific emotions terms.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>nrc <span class="ot">&lt;-</span> <span class="fu">get_sentiments</span>(<span class="st">"nrc"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># checking what proportion of our vocabulary NRC actually covers</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(nrc, <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">matched =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  matched
    &lt;int&gt;
1    1964</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(word) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  total
  &lt;int&gt;
1  4068</code></pre>
</div>
</div>
<p>The NRC lexcion matches is 1,964 out of 4,068 unique words, which the coverage is about 48%. This reflects the expected limitations of applying a modern lexicon to archaic religious text: Egyptian proper nouns, transliterated terms, and archaic English forms fall outside NRC’s vocabulary entirely. The analysis that follows should therefore be read as indicative rather than exhaustive.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># overall emotion distribution across the entire text</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>tidy_death <span class="sc">|&gt;</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(nrc, <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove the broad positive/negative categories — keep only the 8 emotions</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>sentiment <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"positive"</span>, <span class="st">"negative"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sentiment, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sentiment =</span> <span class="fu">reorder</span>(sentiment, n)) <span class="sc">|&gt;</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(n, sentiment, <span class="at">fill =</span> sentiment)) <span class="sc">+</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of word occurrences"</span>,</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Overall emotion profile of the Egyptian Book of the Dead"</span>,</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"NRC lexicon — 8 basic emotions"</span></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(tidy_death, nrc, by = "word"): Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 6 of `x` matches multiple rows in `y`.
ℹ Row 2206 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/Emotion%20profile%20of%20the%20whole%20book-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The dominant emotion across the entire text is <strong>trust</strong>, at over 1,500 word occurrences, followed closely by <strong>joy</strong> and <strong>anticipation</strong>. Fear ranks in the fourth, it is present but is not dominant. This distribution is perhaps counterintuitive for a text concerned with death, but aligns with the text’s core purpose: as Assmann (2005) describes, the Book of the Dead was designed not to dwell on the terror of dying but to reassure and equip the deceased for what follows. The prevalence of trust reflects the repeated invocation of protective deities whose favour the spells seek to secure, while joy and anticipation speak to the promised reward of eternal life.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>tidy_death_sections <span class="ot">&lt;-</span> tidy_death <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(chapter <span class="sc">%in%</span> valid_chapters) <span class="sc">|&gt;</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">section =</span> <span class="fu">case_when</span>(</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">1</span>  <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">14</span>  <span class="sc">~</span> <span class="st">"I: Entering the Underworld"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">15</span> <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">62</span>  <span class="sc">~</span> <span class="st">"II: Mythic Origins &amp; Rebirth"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">63</span> <span class="sc">&amp;</span> chapter <span class="sc">&lt;=</span> <span class="dv">127</span> <span class="sc">~</span> <span class="st">"III: Journey Across the Sky"</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    chapter <span class="sc">&gt;=</span> <span class="dv">128</span>                 <span class="sc">~</span> <span class="st">"IV: Vindication &amp; Power"</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">section =</span> <span class="fu">factor</span>(section, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"I: Entering the Underworld"</span>,</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"II: Mythic Origins &amp; Rebirth"</span>,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"III: Journey Across the Sky"</span>,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IV: Vindication &amp; Power"</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  )))</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a><span class="co"># join with NRC and count emotion words per section</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>section_emotions <span class="ot">&lt;-</span> tidy_death_sections <span class="sc">|&gt;</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(nrc, <span class="at">by =</span> <span class="st">"word"</span>) <span class="sc">|&gt;</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>sentiment <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"positive"</span>, <span class="st">"negative"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(section, sentiment)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(tidy_death_sections, nrc, by = "word"): Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 6 of `x` matches multiple rows in `y`.
ℹ Row 2206 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># normalise by total emotion words in each section</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so sections of different lengths are fairly comparable</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>section_emotions <span class="ot">&lt;-</span> section_emotions <span class="sc">|&gt;</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(section) <span class="sc">|&gt;</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(section_emotions, <span class="fu">aes</span>(<span class="at">x =</span> sentiment, <span class="at">y =</span> proportion, <span class="at">fill =</span> section)) <span class="sc">+</span></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>section, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of emotion words"</span>,</span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Emotion profile by theological section"</span>,</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Proportions allow fair comparison across sections of different lengths"</span></span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/emotion%20by%20section-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Main interpretations:</p>
<ul>
<li><p><strong>Trust</strong> dominates all four sections.</p></li>
<li><p><strong>Fear</strong> is notably higher in Section II than the others.</p></li>
<li><p><strong>Section II</strong> is the most emotionally complex by being closer to each other compared to other sections.</p></li>
<li><p><strong>Anger</strong> is the highest in Section III.</p></li>
</ul>
<p>Comparing the four theological sections reveals a broadly consistent emotional structure, with trust dominant throughout all four sections. Section II stands out as the most emotionally complex as fear rises to its highest point across the entire text, sitting close to anticipation and joy in proportion. This is consistent with the TF-IDF findings from the previous section, where terms like <em>battle</em>, <em>defeat</em> and <em>Sut</em> were most distinctive here. The emotional register reflects a section preoccupied with conflict and its resolution.</p>
<p>Section III records the highest proportion of anger, which aligns with the soul’s active confrontation of adversaries during the solar journey (Assmann, 2005).</p>
<p>By Section IV , trust reaches its peak and fear recedes, suggesting the text’s emotional arc follows the soul’s progression from mythic conflict toward final vindication. The consistency of joy and anticipation across all sections reinforces the overall optimistic orientation observed in the full-text analysis.</p>
<p>Fear and trust are particularly relevant for a funerary text. We are going to plot how their proportions shift across the four sections</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>section_emotions <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sentiment <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"fear"</span>, <span class="st">"trust"</span>, <span class="st">"joy"</span>, <span class="st">"anticipation"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> section, <span class="at">y =</span> proportion, <span class="at">colour =</span> sentiment, <span class="at">group =</span> sentiment)) <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of emotion words"</span>,</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Emotion"</span>,</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Selected emotions across the four theological sections"</span>,</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Trust and fear move in opposition across the soul's journey"</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BozSude_McGarveyClare_TMFinalAssignment_files/figure-html/focusing%20on%20fear%20and%20trust-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Main observations:</p>
<ul>
<li><p><strong>Trust</strong> drops sharply from Section I to II, then recovers strongly to finish highest in Section IV.</p></li>
<li><p><strong>Fear</strong> does the exact opposite with <em>trust</em> ; lowest in Section I, peaks in Section II, then gradually declines to its lowest point in Section IV</p></li>
<li><p><strong>Joy</strong> and <strong>anticipation</strong> both decline from Section I and converge toward the end, remaining relatively stable in Sections III and IV</p></li>
</ul>
<p>The line plot makes the emotional arc of the text immediately visible. <strong>Trust and fear move in near-perfect opposition across the four sections.</strong> Trust begins at its highest point in Section I where the soul’s entry into the underworld, drops sharply as it encounters the mythic conflicts of Section II, then recovers steadily to reach its absolute peak in Section IV.</p>
<p>Fear follows the inverse trajectory: lowest at the outset, it surges in Section II where the Osiris myth and its associated violence dominate, before declining consistently through Sections III and IV. This crossing pattern is the clearest evidence the data offers that the text has a deliberate emotional architecture; one that moves the reader from divine reassurance, through a period of confrontation and danger, and back toward trust and resolution. Joy and anticipation, while present throughout, converge and flatten across the later sections, suggesting they play a supporting rather than structural role in the text’s emotional design.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<section id="main-findings" class="level2">
<h2 class="anchored" data-anchor-id="main-findings">Main Findings</h2>
<p>Two complementary text mining techniques were applied to the <em>Egyptian Book of the Dead</em>: TF-IDF to identify what vocabulary is most distinctive to each section of the text, and NRC sentiment analysis to map the emotional register across the soul’s journey.</p>
<p>The TF-IDF analysis confirmed that the vocabulary shifts meaningfully across the four theological sections established during the Saite Period. Section I is dominated by ceremonial language of reunification and opening ritual; Section II by mythological conflict centred on Osiris, Sut, and Apep; Section III by spatial and procedural language evoking the Field of Reeds; and Section IV by architectural and devotional vocabulary marking final arrival. This vocabulary progression is not random, it maps directly onto the theological narrative that scholars such as Assmann (2005) and Barguet (1967) have described, providing quantitative support for a literary structure that was until now discussed only in qualitative terms.</p>
<p>The sentiment analysis adds an emotional dimension to this finding. Across the full text, trust is the dominant emotion, more present than fear, which might seem counterintuitive in a text about death. This aligns with the text’s function: the Book of the Dead was designed to reassure and equip, not to frighten. Crucially, when broken into sections, trust and fear follow near-perfect opposing trajectories. Trust is highest at the soul’s entry into the underworld and at its final vindication; fear peaks in Section II, precisely where the Osiris myth and its violence are retold. The two analyses are therefore mutually reinforcing: the distinctive words of Section II (battle, defeat, Sut, Apep) explain the emotional spike in fear observed there.</p>
<p>The analysis demonstrates that the <em>Egyptian Book of the Dea</em>d is not simply a collection of disconnected spells but a text with a coherent internal architecture, one that is legible to computational methods. TF-IDF revealed a systematic shift in vocabulary across the four sections of the Saite ordering, while NRC sentiment analysis showed that the emotional register follows an arc from reassurance through conflict and back to resolution. Together, these findings suggest that the compilers of the Book of the Dead exercised real editorial judgment in the sequencing of the spells, producing a text whose emotional and thematic progression mirrors the soul’s journey it describes.</p>
<p>Several limitations should be noted. The NRC lexicon was built on contemporary English and covers only around 48% of the text’s unique vocabulary; archaic and transliterated terms fall entirely outside it. TF-IDF at the section level is also a blunt instrument when sections differ enormously in length. Future analysis could benefit from a domain-specific lexicon for religious or archaic English, and from applying LDA topic modelling to allow the topics to emerge from the text itself rather than being imposed from historical scholarship.</p>
<p>What the analysis does confirm is that 3,000 years after its composition, this funerary text still follows the statistical regularities of natural language, as demonstrated by its conformity to Zipf’s law , while carrying a distinctive theological signal that modern text mining can recover.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Assmann, J. (2005). Death and Salvation in Ancient Egypt. In D. Lorton (Trans.), Cornell University Press eBooks. https://doi.org/10.7591/9780801464805</p>
<p>Barguet, P. (1967). Le livre des morts des anciens Egyptiens.</p>
<p>Hart, G. (1986). The Routledge Dictionary of Egyptian Gods and Goddesses. Routledge &amp; Kegan Paul.</p>
<p>Naville, E. (2022). Introduction. In The Egyptian Book of the Dead. Project Gutenberg.</p>
<p>Taylor, J. H. (2010). Journey through the afterlife: Ancient Egyptian Book of the Dead. Harvard University Press.</p>
<p>The Egyptian Book of the Dead (P. Le Page Renouf &amp; E. Naville, Trans.). (2022). Project Gutenberg. (Original work published 1904)</p>
<p>Wilkinson, R. (2003). The Complete Gods and Goddesses of Ancient Egypt. Thames &amp; Hudson.</p>
<p>Wallis Budge, E. A. (1895). The Book of the Dead: The Papyrus of Ani in the British Museum: The Egyptian Text with Interlinear Transliteration and Translation, a Running Translation, Introduction, Etc.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>